name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Syntax check (py_compile)
        run: |
          python - << 'PY'
          import sys, subprocess, pathlib
          files = [str(p) for p in pathlib.Path('.').rglob('*.py')]
          if not files:
            print("No Python files found.")
            raise SystemExit(0)
          import py_compile
          for f in files:
            py_compile.compile(f, doraise=True)
          print(f"Compiled OK: {len(files)} files")
          PY

      - name: Smoke test main.py (--help)
        run: |
          if [ -f main.py ]; then
            python main.py --help || true
          else
            echo "main.py no existe, se omite"
          fi

      - name: Smoke test app.py (--help)
        run: |
          if [ -f app.py ]; then
            python app.py --help || true
          else
            echo "app.py no existe, se omite"
          fi
